package com.example.zhaolexi.imageloader.redirect.login;
// Generated 2018-5-4 14:48:08 by Hibernate Tools 3.5.0.Final

/**
 * USER_NAME generated by hbm2java
 */
public class User {

    //手机号
    private String uid;
    private String uname;
    private String sessionId;

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

}
